apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: uc1-

images:
  - name: workload-generator
    newName: theodolite/theodolite-uc1-workload-generator
    newTag: latest

bases:
- ../../base

patchesStrategicMerge:
- set_paramters.yaml # Patch setting the resource parameters
