apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-load-generator
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: workload-generator
        env:
        - name: NUM_SENSORS
          value: "4"
        - name: HIERARCHY
          value: "full"
        - name: NUM_NESTED_GROUPS
          value: "5"
        - name: INSTANCES
          value: "1"
