stages:
  - triggers

benchmarks:
  stage: triggers
  trigger:
    include: benchmarks/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: "$CI_COMMIT_TAG"
      when: always
    - changes:
      - benchmarks/*
      when: always
    - when: manual
      allow_failure: true
  