apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-load-generator
spec:
  selector:
    matchLabels:
      app: titan-ccp-load-generator
  replicas: 1
  template:
    metadata:
      labels:
        app: titan-ccp-load-generator
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: workload-generator
        image: theodolite/theodolite-uc2-workload-generator:v0-1-1
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-confluent-cp-kafka:9092"
        - name: HIERARCHY
          value: "full"
        - name: NUM_SENSORS
          value: "4"
        - name: NUM_NESTED_GROUPS
          value: "{{NUM_NESTED_GROUPS}}"
          