apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: titan-ccp-load-generator
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: workload-generator
        env:
        - name: NUM_NESTED_GROUPS
          value: "25000"
