apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-aggregation
spec:
  template:
    spec:
      containers:
      - name: uc1-application
        env:
        - name: COMMIT_INTERVAL_MS
          value: 100
        resources:
          limits:
            memory: 4Gi
            cpu: 1000m
