apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-load-generator
spec:
  selector:
    matchLabels:
      app: titan-ccp-load-generator
  serviceName: titan-ccp-load-generator
  replicas: 1
  template:
    metadata:
      labels:
        app: titan-ccp-load-generator
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: workload-generator
        image: uc-workload-generator:latest
        env:
        - name: ZK_HOST
          value: "my-confluent-cp-zookeeper"
        - name: ZK_PORT
          value: "2181"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-confluent-cp-kafka:9092"
        - name: SCHEMA_REGISTRY_URL
          value: "http://my-confluent-cp-schema-registry:8081"
        - name: NUM_SENSORS
          value: "25000"
        - name: INSTANCES
          value: "1"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
