apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: uc1-

images:
  - name: uc-app
    newName: theodolite/theodolite-uc1-kstreams-app
    newTag: latest

bases:
- ../../base

patchesStrategicMerge:
- set_paramters.yaml # Patch setting the resource parameters
