apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: titan-ccp-load-generator
spec:
  selector:
    matchLabels:
      app: titan-ccp-load-generator
  serviceName: titan-ccp-load-generator
  replicas: 1
  template:
    metadata:
      labels:
        app: titan-ccp-load-generator
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: workload-generator
        image: soerenhenning/uc1-wg:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-confluent-cp-kafka:9092"
        - name: NUM_SENSORS
          value: 25000
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCES
          value: 1
