apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kafka-lag-exporter
    appScope: titan-ccp
  name: kafka-lag-exporter
spec:
  selector:
    matchLabels:
      #app: cp-kafka
      jobLabel: kafka-lag-exporter
  endpoints:
    - port: http
      interval: 5s